### ISSUE TITLE
Errors when starting with no internet connection

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [trembon/switch-library-manager#27] opened 2024-06-01 19:40 UTC
If there is no internet connection, two messages pop up. One error message and another that says there is an update available (which I guess is an error in itself) Can these both get fixed?

Also, the GUI never opens to the desktop when I start it. It always opens minimized to the tray. Is that something only on my end, or a bug that can be fixed?

![error](https://github.com/trembon/switch-library-manager/assets/13652531/be548a81-5b5b-41fb-aa0a-90fd15ff87b7)

![update](https://github.com/trembon/switch-library-manager/assets/13652531/13762189-6a04-497a-89a6-51562f8900f1)

**Comment by trembon** [comment] 2024-06-02 18:07
the internet connection bugs shouldn't be that hard to fix, will look into this

that the app starts minimized i dont know, i havent noticed that behavior, but i will see if i can reproduce. if you want you can create a separate issue for that one, otherwise i will do that when i start look into these

**Comment by trembon** [comment] 2024-06-22 21:05
found that there was an incorrect return path when checking for updates and an error occurred
if an error occur when checking for updates the message will not be shown now and if the error is network related, it will not show an message for that

result should be when starting the app without internet a maximum of one error should appear because of trying to download an updated title database

will be included in the next release or the latest build under the Actions tab

**Closed** 2024-06-22 21:31 UTC
Labels: bug
