### ISSUE TITLE
small bug : in "missing update" tab "update date" colonne is order by month instead of year

### ISSUE THREAD

**Issue by larg000** [trembon/switch-library-manager#37] opened 2024-07-05 19:37 UTC
small bug : in "missing update" tab "update date" colonne is order by month instead of year

**Comment by harvestry-of-ghosts** [comment] 2024-07-06 18:25
@larg000 This was already fixed in a commit two weeks ago. You can see this in the closed issues section under issue #29 . Please check both open and closed issues prior to reporting to make sure it's not already reported and/or fixed. As instructed there, you need to download the latest build from the Actions section.

Please mark as closed. :)

**Comment by larg000** [comment] 2024-07-06 19:21
sorry 
but i don't know and don't undertstand how to download lastest build

**Comment by trembon** [comment] 2024-07-07 08:08
@larg000 you can download the latest files under the "Action" tab here on GitHub, currently this is the link to the latest build: https://github.com/trembon/switch-library-manager/actions/runs/9628416371

and closing as duplicate of #29 as already meantioned

**Closed by trembon** 2024-07-07 08:08 UTC
